#+TITLE: mir

Mir is a package for incremental reading inside Emacs.

* What is Incremental Reading?

Incremental reading is an iterative process of importing,
prioritizing, processing and dismissing text, which is further
referred to as a "topic". A "topic" is any piece of text that you want
to read and extract knowledge from. The incremental reading process
for any given article goes as follows:

1. Importing the article into the system and giving it a /priority/,
   which is its relative importance compared to other material in your
   collection.
2. Reading the article whenever it shows up.
3. Making extracts and/or turning some of the text into permanent
   notes, flashcards, etc.
4. Repeating across many days until you feel that the potential of the
   article is exhausted, at which point you can dismiss it.

Mir automatically schedules reviews for you, thereby decreasing the
effort necesary for further reading. This allows you to increase your
familiarity with the text and strengthen the memory of the concepts
within. However, mir's scope currently does not extend into letting
you turn topics into flashcards or do cloze deletions. This violates
the [[https://supermemo.guru/wiki/Minimum_definition_of_incremental_reading][minimum definition]] of incremental reading. Support for these
features is in the works.

*Caution:* The process of incremental reading is best used with
material that evokes curiosity and is inherently interesting. See the
"Be careful with what you read in mir" section below for more details.

* Installation

** use-package

#+begin_src elisp
  (use-package mir
    :vc "https://github.com/gvalson/mir"
    :commands (mir-import-buffer mir-extract-or-import-from-region)
    :config
    (setq "mir-archive-directory" (expand-file-name "~/Documents/mir")))
#+end_src

** Manual

Ensure that emacs is compiled with SQLite support and that the
following packages are installed:

- =denote=
- =denote-sequence=

Then ensure that mir in your load-path, and put this in your init
file:

#+BEGIN_SRC elisp
  (require 'mir)
#+END_SRC

* Getting Started

** Set =mir-archive-directory=

First of all, choose a folder where you'll keep all your topics.
Everything that you import is saved in this directory as a file, so
make sure that you can access the directory comfortably in case you
want to make any manual adjustments. This variable defaults to
=~/Documents/mir=.

** Import and prioritize your material

Now comes the time to import. You can use the following functions for
this:

- =mir-import-buffer=: Imports the currently opened buffer.
- =mir-extract-or-import-from-region=: Imports the selected part from
  the current buffer.
- =mir-import-from-minibuffer=: Enter your text via the minibuffer and
  import it.
- =mir-import-file=: Select a file and import it as a topic.
- =mir-import-url=: Import a web page as an HTML file (*unstable*).

Each of these commands will ask you to type in a priority. Much like
in [[https://help.supermemo.org/wiki/Glossary:Priority][SuperMemo]], the topic's priority represents its relative importance
and ranges from 0 to 100. More important items have a lower priority
value. Thus, an item with the priority value 0 is the most important
in the collection and will appear earlier than others. If this is your
first day with using mir, stop here. Your imported topics will be
readable tomorrow. If you're wondering why the pause is necessary,
read the "Philosophy" section below.

** Start reading

Next day, run =mir-read= to start reading. You should see a new buffer
show up with one of your imported topics. Feel free to run
=mir-extract-or-import-from-region= to extract an important chunk out
into its own topic and =mir-navigate-to-last-added= to directly jump
to the newly added file. You may also use any other command, as the
buffer is just like any other emacs buffer. When you're done reading
or simply wish to move on, invoke =mir-read-next=. You can continue
until the queue runs out, after which you can either import more items
or do something else.

Generally, you should not worry about topics running out. As you get
more familiar with the process and import more articles, you'll have a
near-endless stream of information. This is why assigning priorities
is important: high-priority items are shown first and will receive
most of your attention.

* Advanced Usage

** COMMENT A general overview of the incremental reading process

# TODO: write about what it is like to do IR; how it evokes curiosity
# and wonder, etc...

** Dismissing Topics

When a topic has exhausted its value, use =mir-dismiss-current-topic=
to dismiss it. A dismissed topic will no longer show up when reading,
but it will still be preserved in =mir-archive-directory= with a
keyword =archive= being added to its file name. The dismissed topic
will also be kept around in the database. Dismissal is preferred over
deletion, as it prevents accidental loss of important topics. Note
that currently there is no way to fully delete topics without manually
changing the database.

** Editing or reprioritizing the current topic

When using mir, you can gradually refine the imported material by
making small changes across each review. To that end, mir provides the
following functions for changing the topic metadata:

- =mir-set-priority=: use this to reprioritize the topic. After
  invoking the command, the topic's actual priority value may be
  slightly different than what you typed since priority values are
  normalized to be evenly distibuted between 0 to 100.
- =mir-set-a-factor=: manually set the A-factor, which governs how
  fast the intervals between reviews grow. If you want to use this,
  make sure to set =mir-scale-a-factor-by-priority= to =nil=.
- =mir-set-title=: change the title of the current topic.
- =mir-reschedule=: Manually reschedule the topic to a set date.

What might be more important to you, however, is changing the topic's
content. There's nothing special necessary to accomplish this: mir
only cares about the file's name in order to make its operations work.
Mir does not check the file's actual content. You're free to edit the
file as you wish (including changing its extension), as long as the ID
at the beginning of the file name is preserved.

Keep in mind that the commands above work on the topic that is
considered as "current" by mir. As of right now, if you navigate to a
different file and invoke the commands, the changes will NOT be made
on the file that you're currently viewing. You can always use =C-h v=
to check the value of =mir--current-topic= to make sure that the
commands you're calling will operate on the file that you wish them
to.

** The difference between rescheduling and changing the priority

Rescheduling via =mir-reschedule= or lowering an element's priority
with =mir-set-priority= may look similar on the surface, but they do
different things.

First, let's examine what changing the element's priority does. Let's
say that the priority was lowered from 10 to 50 (higher value means
lower priority). This means that, on the day when the topic is
scheduled to be shown, it'll be shown much later than other topics.
If, for instance, there are 100 topics that have priority values
10--50, the element will shown right after those 100 topics. Note how,
when changing the priority, nothing changed about scheduling and time.

On the other hand, using =mir-reschedule= makes it so that the element
maintains its priority but it'll be delayed in terms of time. Delaying
a high-priority item is a good way to postpone reviewing it, as the
high priority makes it almost certain that it'll be looked at.

** Randomizing Topics

By default, topics are shown in strictly descending priority order.
This makes it so that the most important topics are displayed first.
However, you may end up in a situation where only a narrow subset of
the topics are shown to you day after day, especially in a larger
collection and especially if you don't review a lot of topics
consistently every day. To remedy that, you can configure the variable
=mir-randomize-topics-ratio=. Its default value is 0.0, meaning that
0% of the queue is randomly shuffled. You can start with 0.2 (meaning
that 20% of the topics in the queue get shuffled) and later adjust to
your preference.

** Writing Your Own Queue Function

If you desire to change how topics are queued for the day, you can
set the value of =mir-query-function= to any function that takes zero
parameters and queries the mir database. Here's some example code:

#+begin_src emacs-lisp
  (setq mir-query-function
        (lambda ()
          (sqlite-select (mir--get-db)
          ;; Make sure to select all the fields from the database.
                         "SELECT * FROM topics WHERE archived = 0 AND priority > 50;")))
#+end_src

** Keeping track of extracts and parents

If you find yourself reading an extract and wanting to look at the
topic where the extract came from, you can use the command
=mir-find-parent=. It leverages the sequence information encoded in
the file name to find and open the parent of the current topic. For
more information, see the manual of =denote-sequence=, which powers
this functionality.

** Customizing the reading experience with the show-topic hook

You can use =mir-show-topic-hook= to do something every time a new
topic is shown. For example, you can make it so that HTML files opened
with =web-mode= get displayed with emacs' built-in web browser =eww=:

#+begin_src elisp
  (add-hook 'mir-show-topic-hook
            (lambda ()
              (when (eq major-mode #'web-mode)
                (let ((current-file (buffer-file-name)))
                  (eww-open-file current-file)
                  ;; Important: vital mir functions won't work without
                  ;; this.
                  (mir-topic-minor-mode)
                  ;; Important: make sure that the eww buffer has a
                  ;; valid `buffer-file-name' value. This is important
                  ;; for making extracts from the buffer.
                  (unless buffer-file-name
                    (setq-local buffer-file-name current-file))))))
#+end_src

** Inspecting the Database

Mir uses SQLite to store scheduling information and review history. By
default, the database file is located in =mir-archive-directory= and
named =mir.db=. The name and location is configurable via
=mir-db-location=. You can use emacs' built-in =sqlite-mode-open-file=
command to inspect the database.

* Philosophy

** Why does mir force me to wait before reading?

By default, imported topics are not scheduled until the day after they
are imported. This is because:

1. There may not be much novel information extracted if you already
   read the topic outside of mir on the same day before importing it.
2. Waiting before looking at the topic allows for the mind to
   consolidate the disparate pieces of knowledge needed to understand
   it. This results in better comprehension and thus more pleasurable
   reading.

This behavior can be changed through the variable
=mir-default-topic-interval=. Set it to 0 to add the imported topics
to the queue immediately.

** Be careful with what you read in mir

Using mir to read some specific material eventually results in you
seeing it many times. This can be both benefitial and detrimental and
that depends on your relationship with the material. If you find the
material incomprehensible, boring, too heavy or generally unsuitable
to your present needs, mir will amplify these feelings tenfold by
showing the material over and over again. Thus, mir is best used with
material that you find inherently interesting---that you'd study even
if no one told you to look into it.

* Resources for Incremental Reading

Note that, presently, all resources about IR assume that you're using
SuperMemo. This is due to the fact that SuperMemo was the first to
implement IR in its entirety.

- [[https://www.youtube.com/channel/UCpkWsnAPl-rhGwUOqdi2Vow][Flashcard Guy (YouTube)]]
- [[https://www.youtube.com/watch?v=oNCLLNZEtz0][What is incremental reading? (youtube)]]
- [[https://www.youtube.com/watch?v=MYz8ya5pKnc][Starting with Incremental Reading by going through the IR Manual]]
- [[https://help.supermemo.org/wiki/Incremental_learning][SuperMemo help: Incremental learning]]

I've also started writing about incremental reading on my website:
[[https://gvalia.xyz/en/wiki/ir/][Incremental Reading]].

* Alternative Software for Incremental Reading

If neither SuperMemo nor mir are your cup of tea, you can get at least
some features of incremental reading with these tools:

1. [[https://www.remnote.com/][RemNote]] with the [[https://github.com/bjsi/incremental-everything][incremental-everything]] plugin.
2. https://dendro.cloud/
3. [[https://apps.ankiweb.net/][Anki]] with this add-on: https://github.com/tvhong/incremental-reading

* Credits

This project was greatly aided by Prot's [[https://github.com/protesilaos/denote/][denote]] and [[https://github.com/protesilaos/denote-sequence][denote-sequence]]
packages. Denote provides a consistent file naming and identification
scheme and tools to work with said scheme, which greatly simplifies
the logic of dealing with unique topics. In addition, denote-sequence
makes working with the tree-like structure of extracts much easier,
allowing for dynamically generating sequence numbers and easy
traversal of the hierarchy.

Incremental reading was pioneered by Piotr Wozniak and SuperMemo.
