name: test

on:
  push:
    branches: [master, feat/**, personal]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ['29.1', '29.4', '30.1']
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: emacs-eldev/setup-eldev@v1

      - name: Test
        run: eldev -dtT test
